name    'Magmatrixx-transmission'
version '0.1.0'
author 'Magmatrixx'
summary 'transmission bittorrent client'
description 'manages the transmission bittorrent client, its web interface and optional block list'
project_page 'https://github.com/Magmatrix/transmission'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
